name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v4.0.0
        with:
          cmd: install # will run `yarn install` command    - name: Run a multi-line script
      - uses: borales/actions-yarn@v4.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v4.0.0
        with:
          cmd: test # will run `yarn test` command
      - name: upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get build artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          FOLDER: build
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages
